[package]
name = "veruna"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "entity", "migration", "view", "repository"]

[dependencies]
actix-web = "4.0.1"
actix-files = "0.6.0"
sailfish = "0.3.4"
env_logger = "0.9"
futures-util = { version = "0.3", default-features = true }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15.0"
sea-orm = { version = "^0.6", features = [
    "sqlx-sqlite",
    "runtime-actix",
    "macros",
    "debug-print"
], default-features = false }

entity = { path = "entity" }
migration = { path = "migration" }
view = { path = "view" }
repository = { path = "repository" }