[package]
name = "veruna"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-rc.2"
sailfish = "0.3.4"
env_logger = "0.9"
futures-util = { version = "0.3", default-features = true}
log = "0.4"
r2d2 = "0.8"
r2d2_sqlite = "0.19"
rusqlite = "0.26"
serde = { version = "1", features = ["derive"] }
serde_json = "1"