[package]
name = "veruna"
version = "1.0.0"
edition = "2021"
description = "Veruna project"
license = "MIT OR Apache-2.0"
authors = ["Alexander Averichev <averichev@yandex.ru>"]
keywords = ["veruna"]
repository = "https://github.com/averichev/veruna"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veruna-kernel = { version = "1.1.15" }
veruna-data = { version = "1.0.1" }
assert-str = "0.1.0"
url = "2.3.1"
actix-web = "4"