[package]
name = "veruna-domain"
version = "1.0.0"
edition = "2021"

[dependencies]
url = { version = "2.3.1" }
async-trait = "0.1.59"
log = "0.*"
serde = "1.0.166"
crossbeam-channel = "0.5.8"
tokio = { version = "1.29.1" }
argon2 = "0.5.1"
typetag = "0.2.12"